import React, { useMemo, useState } from 'react';
import {
  ActivityIndicator,
  Alert,
  Platform,
  ScrollView,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from 'react-native';
import { useLocalSearchParams } from 'expo-router';
import { Download, Users } from 'lucide-react-native';
import Toast from 'react-native-toast-message';
import * as XLSX from 'xlsx';
import * as FileSystem from 'expo-file-system';
import * as Sharing from 'expo-sharing';

import { useTheme } from '../hooks/useTheme';
import useStudents from '../hooks/useStudents';
import useFees, { type FeeRecord } from '../hooks/useFees';
import { useAttendance } from '../hooks/useAttendance';
import { useTenant } from '../hooks/useTenantContext';
import { useAuth } from '../hooks/useAuthUnified';
import { dataManagementService } from '../services/dataManagementService';
import type { Student, Tenant } from '../types';

const REPORT_TIMESTAMP_FORMATTER = new Intl.DateTimeFormat('en-IN', {
  year: 'numeric',
  month: '2-digit',
  day: '2-digit',
  hour: '2-digit',
  minute: '2-digit',
});

const formatDate = (value?: string | null) => {
  if (!value) return 'N/A';
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) {
    return 'N/A';
  }
  return date.toLocaleDateString('en-IN', { year: 'numeric', month: 'short', day: 'numeric' });
};

const formatCurrency = (value?: number | null) => {
  if (!value || Number.isNaN(value)) {
    return 0;
  }
  return Number(value);
};

const sanitizeTenantPrefix = (value?: string | null) => {
  if (!value) {
    return null;
  }
  const trimmed = value.trim();
  if (!trimmed) {
    return null;
  }
  return trimmed.replace(/[^A-Za-z0-9_-]/g, '-');
};

const buildFileName = (base: string, tenantHint?: string | null) => {
  const now = new Date();
  const [datePart, timePart] = REPORT_TIMESTAMP_FORMATTER.format(now).split(', ');
  const safeTime = timePart?.replace(/[:\s]/g, '-') ?? now.getTime();
  const safeDate = datePart?.replaceAll('/', '-') ?? 'date';
  const tenantPrefix = sanitizeTenantPrefix(tenantHint);
  const label = tenantPrefix ? `${tenantPrefix}_${base}` : base;
  return `${label}_${safeDate}_${safeTime}.xlsx`;
};

async function exportWorkbook(workbook: XLSX.WorkBook, baseName: string, tenantHint?: string | null) {
  const wbout = XLSX.write(workbook, { type: 'base64', bookType: 'xlsx' });
  const fileName = buildFileName(baseName, tenantHint);

  if (Platform.OS === 'web') {
    const binary = atob(wbout);
    const bytes = new Uint8Array(binary.length);
    for (let i = 0; i < binary.length; i += 1) {
      bytes[i] = binary.charCodeAt(i);
    }
    const blob = new Blob([bytes], {
      type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = fileName;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    window.URL.revokeObjectURL(url);
    return fileName;
  }

  const fileUri = `${FileSystem.documentDirectory}${fileName}`;
  await FileSystem.writeAsStringAsync(fileUri, wbout, {
    encoding: FileSystem.EncodingType.Base64,
  });

  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(fileUri, {
      mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      dialogTitle: 'Share exported report',
      UTI: 'com.microsoft.excel.xlsx',
    });
  }

  return fileUri;
}

type TenantMetadataSheetOptions = {
  tenant: Tenant | null;
  membershipRole?: string | null;
  generatedBy?: string | null;
  datasetLabel: string;
  generatedAt: Date;
  stats?: Record<string, string | number>;
};

function appendTenantMetadataSheet(workbook: XLSX.WorkBook, options: TenantMetadataSheetOptions) {
  const rows: { Field: string; Value: string | number }[] = [
    { Field: 'Dataset', Value: options.datasetLabel },
    { Field: 'Generated At', Value: REPORT_TIMESTAMP_FORMATTER.format(options.generatedAt) },
    { Field: 'Local Timezone', Value: Intl.DateTimeFormat().resolvedOptions().timeZone },
  ];

  if (options.generatedBy) {
    rows.push({ Field: 'Generated By', Value: options.generatedBy });
  }

  if (options.membershipRole) {
    rows.push({ Field: 'Access Role', Value: options.membershipRole });
  }

  const tenant = options.tenant;
  rows.push({ Field: 'Tenant Name', Value: tenant?.name ?? 'Unknown coaching center' });
  rows.push({ Field: 'Tenant Code', Value: tenant?.code ?? '—' });
  rows.push({ Field: 'Tenant ID', Value: tenant?.id ?? '—' });
  rows.push({ Field: 'Tenant Status', Value: tenant?.status ?? '—' });
  rows.push({ Field: 'Billing Tier', Value: tenant?.billingTier ?? '—' });

  if (tenant?.defaultCurrency) {
    rows.push({ Field: 'Default Currency', Value: tenant.defaultCurrency });
  }

  if (options.stats) {
    Object.entries(options.stats).forEach(([key, value]) => {
      rows.push({ Field: key, Value: value });
    });
  }

  const sheet = XLSX.utils.json_to_sheet(rows);
  sheet['!cols'] = [{ wch: 28 }, { wch: 36 }];
  XLSX.utils.book_append_sheet(workbook, sheet, 'Tenant Metadata');
}

const chipLabelFromSource = (source?: string) => {
  switch (source) {
    case 'students':
      return 'Jumped from Students tab';
    case 'fees':
      return 'Jumped from Fees tab';
    default:
      return undefined;
  }
};

type DownloadInProgress = 'students' | 'fees' | 'archive' | null;

type GradeAggregation = {
  count: number;
  totalFees: number;
  paidFees: number;
  attendanceSum: number;
  attendanceCount: number;
};

const DownloadReportsPage: React.FC = () => {
  const { theme } = useTheme();
  const { students, loading: studentsLoading, error: studentsError } = useStudents();
  const { fees, loading: feesLoading, error: feesError } = useFees();
  const { user } = useAuth();

  const studentIds = useMemo(
    () => students.map((student) => student.id).filter((id): id is string => !!id),
    [students],
  );

  const {
    loading: attendanceLoading,
    getAttendancePercentage,
    getDaysPresent,
  } = useAttendance(studentIds);
  const { activeTenant, activeMembership, loading: tenantLoading } = useTenant();

  const tenantExportGuardMessage = useMemo(() => {
    if (tenantLoading) {
      return 'Loading coaching center context…';
    }
    if (!activeTenant) {
      return 'Select a coaching center before exporting reports.';
    }
    if (!activeMembership || activeMembership.status !== 'active') {
      return 'Exports unlock after your membership is approved.';
    }
    if (!['owner', 'admin', 'staff'].includes(activeMembership.role)) {
      return 'Only staff, admins, or owners can export reports.';
    }
    return null;
  }, [tenantLoading, activeTenant, activeMembership]);

  const tenantExportDisabled = Boolean(tenantExportGuardMessage);
  const tenantGuardIsLoading = tenantLoading && tenantExportDisabled;
  const tenantFileNameHint = activeTenant ? activeTenant.slug ?? activeTenant.code ?? activeTenant.id ?? null : null;
  const tenantGeneratedBy = activeMembership?.email ?? null;
  const tenantRole = activeMembership?.role ?? null;
  const exportRequesterEmail = tenantGeneratedBy ?? user?.email ?? null;
  const resolvedTenantGuardMessage = tenantExportGuardMessage ?? 'Select a coaching center before exporting reports.';

  const [downloading, setDownloading] = useState<DownloadInProgress>(null);
  const params = useLocalSearchParams<{ source?: string }>();
  const sourceLabel = chipLabelFromSource(typeof params.source === 'string' ? params.source : undefined);

  const studentCount = students.length;
  const feeCount = fees.length;

  const feeTotals = useMemo(() => {
    let totalAmount = 0;
    let totalPaid = 0;

    fees.forEach((fee) => {
      totalAmount += formatCurrency(fee.amount);
      totalPaid += formatCurrency(fee.paidAmount);
    });

    return {
      totalAmount,
      totalPaid,
      pendingAmount: Math.max(totalAmount - totalPaid, 0),
    };
  }, [fees]);

  const handleStudentReport = async () => {
    if (tenantExportDisabled) {
      Alert.alert('Export unavailable', resolvedTenantGuardMessage);
      return;
    }
    if (!students.length) {
      Alert.alert('No students found', 'Add student records before exporting reports.');
      return;
    }

    setDownloading('students');
    Toast.show({
      type: 'info',
      text1: 'Generating student report…',
      text2: 'Compiling profiles, attendance, and fee insights.',
      position: 'top',
      visibilityTime: 2200,
    });

    try {
      const studentRows = students.map((student: Student, index: number) => {
        const attendancePercent = getAttendancePercentage(student.id) ?? student.attendance ?? 0;
        const attendanceBreakdown = getDaysPresent(student.id);
        const presentDays = attendanceBreakdown?.present ?? 0;
        const totalDays = attendanceBreakdown?.total ?? 0;

        return {
          'Sr. No.': index + 1,
          'Student Name': student.name,
          Grade: student.grade ?? 'N/A',
          Email: student.email ?? 'N/A',
          Phone: student.phone ?? 'N/A',
          'Parent Name': student.parentName ?? 'N/A',
          'Parent Contact': student.parentContact ?? student.parentPhone ?? 'N/A',
          'Monthly Fee (₹)': formatCurrency(student.monthlyFee),
          'Total Fees (₹)': formatCurrency(student.totalFees),
          'Fees Paid (₹)': formatCurrency(student.feesPaid),
          'Outstanding (₹)': formatCurrency((student.totalFees || 0) - (student.feesPaid || 0)),
          'Attendance %': `${Math.round(attendancePercent)}%`,
          'Attendance Days': `${presentDays}/${totalDays}`,
          'Performance': student.performance ?? 'N/A',
          Status: student.status ?? 'active',
          'Enrollment Date': formatDate(student.enrollmentDate || student.joinDate),
          'Last Updated': formatDate(student.updatedAt),
          Subjects: (student.subjects ?? []).join(', ') || 'N/A',
        };
      });

      const totalStudents = students.length;
      const activeStudents = students.filter((student) => student.status === 'active').length;
      const inactiveStudents = students.filter((student) => student.status === 'inactive').length;
      const suspendedStudents = students.filter((student) => student.status === 'suspended').length;

      const calculatedAttendances = students
        .map((student) => getAttendancePercentage(student.id) ?? student.attendance ?? 0)
        .filter((percentage) => percentage > 0);

      const averageAttendance = calculatedAttendances.length
        ? calculatedAttendances.reduce((sum, percentage) => sum + percentage, 0) / calculatedAttendances.length
        : 0;

      const summaryRows = [
        { Metric: 'Total Students', Value: totalStudents },
        { Metric: 'Active Students', Value: activeStudents },
        { Metric: 'Inactive Students', Value: inactiveStudents },
        { Metric: 'Suspended Students', Value: suspendedStudents },
        { Metric: 'Average Attendance', Value: `${Math.round(averageAttendance)}%` },
      ];

      const gradeAggregation = students.reduce<Record<string, GradeAggregation>>((acc, student) => {
        const grade = student.grade || 'Unassigned';
        if (!acc[grade]) {
          acc[grade] = {
            count: 0,
            totalFees: 0,
            paidFees: 0,
            attendanceSum: 0,
            attendanceCount: 0,
          };
        }
        const bucket = acc[grade];
        bucket.count += 1;
        bucket.totalFees += formatCurrency(student.totalFees);
        bucket.paidFees += formatCurrency(student.feesPaid);
        const attendancePercent = getAttendancePercentage(student.id) ?? student.attendance ?? 0;
        if (attendancePercent > 0) {
          bucket.attendanceSum += attendancePercent;
          bucket.attendanceCount += 1;
        }
        return acc;
      }, {});

      const gradeRows = Object.entries(gradeAggregation).map(([grade, stats]) => ({
        Grade: grade,
        'Student Count': stats.count,
        'Total Fees (₹)': stats.totalFees,
        'Fees Collected (₹)': stats.paidFees,
        'Outstanding (₹)': Math.max(stats.totalFees - stats.paidFees, 0),
        'Average Attendance %': stats.attendanceCount
          ? Math.round(stats.attendanceSum / stats.attendanceCount)
          : 'N/A',
      }));

      const workbook = XLSX.utils.book_new();

      appendTenantMetadataSheet(workbook, {
        tenant: activeTenant,
        membershipRole: tenantRole,
        generatedBy: tenantGeneratedBy,
        datasetLabel: 'Student performance report',
        generatedAt: new Date(),
        stats: {
          'Total Students': totalStudents,
          'Active Students': activeStudents,
          'Inactive Students': inactiveStudents,
          'Suspended Students': suspendedStudents,
          'Average Attendance %': `${Math.round(averageAttendance)}%`,
        },
      });

      const summarySheet = XLSX.utils.json_to_sheet(summaryRows);
      summarySheet['!cols'] = [{ wch: 28 }, { wch: 18 }];
      XLSX.utils.book_append_sheet(workbook, summarySheet, 'Summary');

      const studentsSheet = XLSX.utils.json_to_sheet(studentRows);
      studentsSheet['!cols'] = Array.from({ length: 17 }, () => ({ wch: 22 }));
      XLSX.utils.book_append_sheet(workbook, studentsSheet, 'Student Details');

      if (gradeRows.length) {
        const gradeSheet = XLSX.utils.json_to_sheet(gradeRows);
        gradeSheet['!cols'] = Array.from({ length: 5 }, () => ({ wch: 20 }));
        XLSX.utils.book_append_sheet(workbook, gradeSheet, 'Grade Overview');
      }

      const location = await exportWorkbook(workbook, 'Student_Report', tenantFileNameHint);

      Toast.show({
        type: 'success',
        text1: 'Student report ready!',
        text2: `Saved as ${location.split('/').pop()}`,
        position: 'top',
        visibilityTime: 3200,
      });
    } catch (error) {
      console.error('Student report export failed', error);
      Toast.show({
        type: 'error',
        text1: 'Export failed',
        text2: 'Could not generate student report. Please try again.',
        position: 'top',
        visibilityTime: 3500,
      });
    } finally {
      setDownloading(null);
    }
  };

  const handleFeeReport = async () => {
    if (tenantExportDisabled) {
      Alert.alert('Export unavailable', resolvedTenantGuardMessage);
      return;
    }
    if (!fees.length) {
      Alert.alert('No fee records', 'Add fee entries before exporting reports.');
      return;
    }

    setDownloading('fees');
    Toast.show({
      type: 'info',
      text1: 'Generating fee report…',
      text2: 'Aggregating invoices, payments, and student breakdown.',
      position: 'top',
      visibilityTime: 2200,
    });

    try {
      const studentLookup = students.reduce<Record<string, Student>>((acc, student) => {
        if (student.id) {
          acc[student.id] = student;
        }
        return acc;
      }, {});

      const detailedRows = fees.map((fee: FeeRecord, index: number) => {
        const student = fee.studentId ? studentLookup[fee.studentId] : undefined;
        const totalAmount = formatCurrency(fee.amount);
        const paidAmount = formatCurrency(fee.paidAmount);
        const pendingAmount = Math.max(totalAmount - paidAmount, 0);

        return {
          'Sr. No.': index + 1,
          'Student Name': student?.name ?? fee.studentName ?? 'Unknown student',
          Grade: student?.grade ?? 'N/A',
          'Fee Type': fee.type ?? 'tuition',
          Description: fee.description ?? 'N/A',
          'Total Amount (₹)': totalAmount,
          'Paid Amount (₹)': paidAmount,
          'Pending Amount (₹)': pendingAmount,
          Status:
            fee.status
            || (pendingAmount === 0 ? 'paid' : paidAmount > 0 ? 'partial' : 'pending'),
          'Due Date': formatDate(fee.dueDate),
          'Paid Date': formatDate(fee.paidDate),
          'Months Covered': (fee.monthsCovered ?? []).join(', '),
          'Created On': formatDate(fee.createdAt),
          'Last Updated': formatDate(fee.updatedAt),
        };
      });

      const { totalAmount, totalPaid, pendingAmount } = feeTotals;

      const overviewRows = [
        { Metric: 'Total Fee Records', Value: fees.length },
        { Metric: 'Total Invoice Amount (₹)', Value: totalAmount },
        { Metric: 'Total Paid (₹)', Value: totalPaid },
        { Metric: 'Outstanding Amount (₹)', Value: pendingAmount },
      ];

      const statusBreakdown = fees.reduce<Record<string, number>>((acc, fee) => {
        const key = fee.status ?? 'pending';
        acc[key] = (acc[key] ?? 0) + 1;
        return acc;
      }, {});

      const statusRows = Object.entries(statusBreakdown).map(([status, count]) => ({
        Status: status,
        Records: count,
      }));

      const studentContribution = fees.reduce<Record<string, { name: string; total: number; paid: number }>>(
        (acc, fee) => {
          const student = fee.studentId ? studentLookup[fee.studentId] : undefined;
          const key = student?.id ?? fee.studentId ?? fee.studentName ?? `student-${fee.id}`;
          if (!acc[key]) {
            acc[key] = {
              name: student?.name ?? fee.studentName ?? 'Unknown student',
              total: 0,
              paid: 0,
            };
          }
          acc[key].total += formatCurrency(fee.amount);
          acc[key].paid += formatCurrency(fee.paidAmount);
          return acc;
        },
        {},
      );

      const studentRows = Object.values(studentContribution).map((entry) => ({
        Student: entry.name,
        'Total Invoiced (₹)': entry.total,
        'Paid (₹)': entry.paid,
        'Outstanding (₹)': Math.max(entry.total - entry.paid, 0),
      }));

      const workbook = XLSX.utils.book_new();

      appendTenantMetadataSheet(workbook, {
        tenant: activeTenant,
        membershipRole: tenantRole,
        generatedBy: tenantGeneratedBy,
        datasetLabel: 'Fee analytics report',
        generatedAt: new Date(),
        stats: {
          'Fee Records': fees.length,
          'Total Invoice Amount (₹)': `₹${totalAmount.toLocaleString('en-IN')}`,
          'Total Paid (₹)': `₹${totalPaid.toLocaleString('en-IN')}`,
          'Outstanding (₹)': `₹${pendingAmount.toLocaleString('en-IN')}`,
        },
      });

      const overviewSheet = XLSX.utils.json_to_sheet(overviewRows);
      overviewSheet['!cols'] = [{ wch: 32 }, { wch: 18 }];
      XLSX.utils.book_append_sheet(workbook, overviewSheet, 'Executive Summary');

      const detailSheet = XLSX.utils.json_to_sheet(detailedRows);
      detailSheet['!cols'] = Array.from({ length: 12 }, () => ({ wch: 22 }));
      XLSX.utils.book_append_sheet(workbook, detailSheet, 'Fee Details');

      if (statusRows.length) {
        const statusSheet = XLSX.utils.json_to_sheet(statusRows);
        statusSheet['!cols'] = [{ wch: 16 }, { wch: 14 }];
        XLSX.utils.book_append_sheet(workbook, statusSheet, 'Status Breakdown');
      }

      if (studentRows.length) {
        const studentSheet = XLSX.utils.json_to_sheet(studentRows);
        studentSheet['!cols'] = Array.from({ length: 4 }, () => ({ wch: 24 }));
        XLSX.utils.book_append_sheet(workbook, studentSheet, 'By Student');
      }

      const location = await exportWorkbook(workbook, 'Fee_Report', tenantFileNameHint);

      Toast.show({
        type: 'success',
        text1: 'Fee report ready!',
        text2: `Saved as ${location.split('/').pop()}`,
        position: 'top',
        visibilityTime: 3200,
      });
    } catch (error) {
      console.error('Fee report export failed', error);
      Toast.show({
        type: 'error',
        text1: 'Export failed',
        text2: 'Could not generate fee report. Please try again.',
        position: 'top',
        visibilityTime: 3500,
      });
    } finally {
      setDownloading(null);
    }
  };

  const handleTenantArchiveExport = async () => {
    if (tenantExportDisabled) {
      Alert.alert('Export unavailable', resolvedTenantGuardMessage);
      return;
    }
    if (!activeTenant?.id) {
      Alert.alert('Missing coaching center', 'Select a coaching center before exporting data.');
      return;
    }
    if (!exportRequesterEmail) {
      Alert.alert('Sign in again', 'We could not verify your account email for this export. Please re-authenticate.');
      return;
    }

    setDownloading('archive');
    Toast.show({
      type: 'info',
      text1: 'Preparing tenant export…',
      text2: 'Fetching a secure snapshot from the backend.',
      position: 'top',
      visibilityTime: 2200,
    });

    try {
      const payload = await dataManagementService.exportAllData(activeTenant.id, exportRequesterEmail);
      const jsonString = JSON.stringify(payload, null, 2);
      const fileName = dataManagementService.generateExportFilename(
        tenantFileNameHint ? `${tenantFileNameHint}_tenant_export` : 'tenant_export',
      );

      if (Platform.OS === 'web') {
        const blob = new Blob([jsonString], { type: 'application/json' });
        const url = window.URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = fileName;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        window.URL.revokeObjectURL(url);
      } else {
        const fileUri = `${FileSystem.documentDirectory}${fileName}`;
        await FileSystem.writeAsStringAsync(fileUri, jsonString, {
          encoding: FileSystem.EncodingType.UTF8,
        });
        if (await Sharing.isAvailableAsync()) {
          await Sharing.shareAsync(fileUri, {
            mimeType: 'application/json',
            dialogTitle: 'Share tenant export',
            UTI: 'public.json',
          });
        }
      }

      Toast.show({
        type: 'success',
        text1: 'Tenant archive ready!',
        text2: `Saved as ${fileName}`,
        position: 'top',
        visibilityTime: 3200,
      });
      void dataManagementService.cleanupOldBackups(activeTenant.id);
    } catch (error) {
      console.error('Tenant export failed', error);
      const message = error instanceof Error ? error.message : 'Unable to export tenant data. Please try again.';
      Alert.alert('Export failed', message);
      Toast.show({
        type: 'error',
        text1: 'Export failed',
        text2: message,
        position: 'top',
        visibilityTime: 3500,
      });
    } finally {
      setDownloading(null);
    }
  };

  const studentButtonDisabled =
    tenantExportDisabled || downloading !== null || studentsLoading || attendanceLoading || !!studentsError;
  const feeButtonDisabled = tenantExportDisabled || downloading !== null || feesLoading || !!feesError;
  const archiveButtonDisabled = tenantExportDisabled || downloading !== null;

  return (
    <ScrollView
      style={[styles.container, { backgroundColor: theme.background }]}
      contentContainerStyle={styles.content}
      showsVerticalScrollIndicator={false}
    >
      {sourceLabel && (
        <View
          style={[
            styles.sourceChip,
            { backgroundColor: `${theme.primary}15`, borderColor: `${theme.primary}30` },
          ]}
        >
          <Text style={[styles.sourceChipText, { color: theme.primary }]}>{sourceLabel}</Text>
        </View>
      )}

      <View
        style={[styles.heroCard, { backgroundColor: theme.surface }]}
        accessible
        accessibilityRole="summary"
      >
        <Text style={[styles.heroTitle, { color: theme.text }]}>Download Reports</Text>
        <Text style={[styles.heroSubtitle, { color: theme.textSecondary }]}>
          Export curated Excel workbooks for audits, compliance submissions, and sharing insights
          with parents or stakeholders. Each export bundles multiple sheets and ready-to-share
          summaries.
        </Text>
      </View>

        {tenantExportDisabled && (
          <View
            style={[
              styles.warningCard,
              {
                backgroundColor: tenantGuardIsLoading ? `${theme.primary}10` : `${theme.error}10`,
                borderColor: tenantGuardIsLoading ? `${theme.primary}25` : `${theme.error}25`,
              },
            ]}
          >
            <Text
              style={[
                styles.warningTitle,
                { color: tenantGuardIsLoading ? theme.primary : theme.error },
              ]}
            >
              {tenantGuardIsLoading ? 'Preparing exports' : 'Exports locked'}
            </Text>
            <Text style={[styles.warningSubtitle, { color: theme.textSecondary }]}>
              {resolvedTenantGuardMessage}
            </Text>
          </View>
        )}

      <View style={styles.statsRow}>
        <View
          style={[styles.statCard, { backgroundColor: theme.surface }]}
          accessible
          accessibilityLabel={`Total students ${studentCount}`}
        >
          <Text style={[styles.statLabel, { color: theme.textSecondary }]}>Students synced</Text>
          <Text style={[styles.statValue, { color: theme.text }]}>{studentCount}</Text>
        </View>
        <View
          style={[styles.statCard, { backgroundColor: theme.surface }]}
          accessible
          accessibilityLabel={`Fee records ${feeCount}`}
        >
          <Text style={[styles.statLabel, { color: theme.textSecondary }]}>Fee records</Text>
          <Text style={[styles.statValue, { color: theme.text }]}>{feeCount}</Text>
        </View>
        <View
          style={[styles.statCard, { backgroundColor: theme.surface }]}
          accessible
          accessibilityLabel={`Outstanding amount ₹${feeTotals.pendingAmount.toLocaleString('en-IN')}`}
        >
          <Text style={[styles.statLabel, { color: theme.textSecondary }]}>Outstanding</Text>
          <Text style={[styles.statValue, { color: theme.error }]}>
            ₹{feeTotals.pendingAmount.toLocaleString('en-IN')}
          </Text>
        </View>
      </View>

      {(studentsError || feesError) && (
        <View
          style={[
            styles.warningCard,
            {
              backgroundColor: `${theme.error}10`,
              borderColor: `${theme.error}25`,
            },
          ]}
        >
          <Text style={[styles.warningTitle, { color: theme.error }]}>Heads up</Text>
          <Text style={[styles.warningSubtitle, { color: theme.textSecondary }]}>
            {studentsError ?? feesError}
          </Text>
        </View>
      )}

      <View style={[styles.reportCard, { backgroundColor: theme.surface }]}
        accessibilityRole="summary"
      >
        <View style={styles.reportHeader}>
          <View style={[styles.iconContainer, { backgroundColor: `${theme.primary}15` }]}>
            <Users size={24} color={theme.primary} />
          </View>
          <View style={{ flex: 1 }}>
            <Text style={[styles.reportTitle, { color: theme.text }]}>Student performance report</Text>
            <Text style={[styles.reportSubtitle, { color: theme.textSecondary }]}>
              Comprehensive roster including guardians, attendance insights, academic status, and
              fee commitments for each learner.
            </Text>
          </View>
        </View>

        <View style={styles.reportMetaRow}>
          <View
            style={[styles.metaPill, { borderColor: theme.border }]}
            accessible
            accessibilityLabel={`Includes ${studentCount} students`}
          >
            <Text style={[styles.metaText, { color: theme.textSecondary }]}>
              {studentCount} students
            </Text>
          </View>
          <View
            style={[styles.metaPill, { borderColor: theme.border }]}
            accessible
            accessibilityLabel="Three sheets: summary, details, grades"
          >
            <Text style={[styles.metaText, { color: theme.textSecondary }]}>3 sheets</Text>
          </View>
        </View>

        <TouchableOpacity
          style={[styles.downloadButton, { backgroundColor: theme.primary }]}
          onPress={handleStudentReport}
          disabled={studentButtonDisabled}
          accessibilityRole="button"
          accessibilityLabel="Download student report"
        >
          {downloading === 'students' ? (
            <ActivityIndicator color="#ffffff" />
          ) : (
            <Download size={18} color="#ffffff" />
          )}
          <Text style={[styles.downloadText, { color: '#ffffff' }]}>Download student report</Text>
        </TouchableOpacity>
      </View>

      <View style={[styles.reportCard, { backgroundColor: theme.surface }]}>
        <View style={styles.reportHeader}>
          <View style={[styles.iconContainer, { backgroundColor: `${theme.primary}15` }]}>
            <Download size={24} color={theme.primary} />
          </View>
          <View style={{ flex: 1 }}>
            <Text style={[styles.reportTitle, { color: theme.text }]}>Fee analytics report</Text>
            <Text style={[styles.reportSubtitle, { color: theme.textSecondary }]}>
              Detailed ledger of invoices, payment status, and student-wise recoveries with ready
              summaries for audits.
            </Text>
          </View>
        </View>

        <View style={styles.reportMetaRow}>
          <View style={[styles.metaPill, { borderColor: theme.border }]}>
            <Text style={[styles.metaText, { color: theme.textSecondary }]}>
              {feeCount} fee records
            </Text>
          </View>
          <View style={[styles.metaPill, { borderColor: theme.border }]}>
            <Text style={[styles.metaText, { color: theme.textSecondary }]}>
              Outstanding ₹{feeTotals.pendingAmount.toLocaleString('en-IN')}
            </Text>
          </View>
        </View>

        <TouchableOpacity
          style={[styles.downloadButton, { backgroundColor: theme.primary }]}
          onPress={handleFeeReport}
          disabled={feeButtonDisabled}
          accessibilityRole="button"
          accessibilityLabel="Download fee report"
        >
          {downloading === 'fees' ? (
            <ActivityIndicator color="#ffffff" />
          ) : (
            <Download size={18} color="#ffffff" />
          )}
          <Text style={[styles.downloadText, { color: '#ffffff' }]}>Download fee report</Text>
        </TouchableOpacity>
      </View>

      <View style={[styles.reportCard, { backgroundColor: theme.surface }]}
        accessibilityRole="summary"
      >
        <View style={styles.reportHeader}>
          <View style={[styles.iconContainer, { backgroundColor: `${theme.primary}15` }]}>
            <Download size={24} color={theme.primary} />
          </View>
          <View style={{ flex: 1 }}>
            <Text style={[styles.reportTitle, { color: theme.text }]}>Full tenant archive (JSON)</Text>
            <Text style={[styles.reportSubtitle, { color: theme.textSecondary }]}>Secure snapshot direct from the backend runtime including students, fees, attendance, devices, notifications, and membership rosters.</Text>
          </View>
        </View>

        <View style={styles.reportMetaRow}>
          <View style={[styles.metaPill, { borderColor: theme.border }]}>
            <Text style={[styles.metaText, { color: theme.textSecondary }]}>Requires staff access</Text>
          </View>
          <View style={[styles.metaPill, { borderColor: theme.border }]}>
            <Text style={[styles.metaText, { color: theme.textSecondary }]}>JSON + gzip ready</Text>
          </View>
        </View>

        <TouchableOpacity
          style={[styles.downloadButton, { backgroundColor: theme.primary }]}
          onPress={handleTenantArchiveExport}
          disabled={archiveButtonDisabled}
          accessibilityRole="button"
          accessibilityLabel="Download full tenant export"
        >
          {downloading === 'archive' ? (
            <ActivityIndicator color="#ffffff" />
          ) : (
            <Download size={18} color="#ffffff" />
          )}
          <Text style={[styles.downloadText, { color: '#ffffff' }]}>Download tenant export</Text>
        </TouchableOpacity>
      </View>

      <View
        style={[styles.heroCard, { backgroundColor: theme.surface }]}
        accessible
        accessibilityRole="text"
      >
        <Text style={[styles.heroSubtitle, { color: theme.textSecondary }]}>
          Need a customised export? Reach out to support and we can help craft a report for your
          next review meeting.
        </Text>
      </View>
    </ScrollView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  content: {
    paddingHorizontal: 20,
    paddingVertical: 24,
    gap: 20,
  },
  heroCard: {
    borderRadius: 20,
    padding: 20,
    shadowColor: '#000000',
    shadowOpacity: 0.05,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
    gap: 8,
  },
  heroTitle: {
    fontSize: 20,
    fontFamily: 'Inter-SemiBold',
  },
  heroSubtitle: {
    fontSize: 14,
    fontFamily: 'Inter-Medium',
    lineHeight: 20,
  },
  sourceChip: {
    alignSelf: 'flex-start',
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  sourceChipText: {
    fontSize: 12,
    fontFamily: 'Inter-Medium',
  },
  statsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  statCard: {
    flex: 1,
    minWidth: 140,
    borderRadius: 16,
    padding: 16,
    gap: 6,
  },
  statLabel: {
    fontSize: 12,
    fontFamily: 'Inter-Medium',
  },
  statValue: {
    fontSize: 20,
    fontFamily: 'Inter-Bold',
  },
  warningCard: {
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    gap: 4,
  },
  warningTitle: {
    fontSize: 14,
    fontFamily: 'Inter-SemiBold',
  },
  warningSubtitle: {
    fontSize: 13,
    fontFamily: 'Inter-Medium',
    lineHeight: 18,
  },
  reportCard: {
    borderRadius: 20,
    padding: 20,
    gap: 16,
    shadowColor: '#000000',
    shadowOpacity: 0.04,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 1,
  },
  reportHeader: {
    flexDirection: 'row',
    gap: 16,
    alignItems: 'center',
  },
  iconContainer: {
    width: 48,
    height: 48,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  reportTitle: {
    fontSize: 16,
    fontFamily: 'Inter-SemiBold',
  },
  reportSubtitle: {
    fontSize: 13,
    fontFamily: 'Inter-Medium',
    lineHeight: 18,
  },
  reportMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  metaPill: {
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  metaText: {
    fontSize: 12,
    fontFamily: 'Inter-Medium',
  },
  downloadButton: {
    borderRadius: 14,
    paddingVertical: 14,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 10,
  },
  downloadText: {
    fontSize: 15,
    fontFamily: 'Inter-SemiBold',
  },
});

export default DownloadReportsPage;