# fly.toml app configuration file generated for weathered-frog-2202 on 2025-08-27T12:15:29+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'my-email-backend'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '8090'

[http_service]
  internal_port = 8090
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
